services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.28.2
    container_name: zerobyte
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=Australia/Melbourne # Set your timezone here
      - BASE_URL=http://localhost:4096 # URL you will use to access Zerobyte
      - APP_SECRET=${} # Generate your own secret with `openssl rand -hex 32`
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - /opt/production:/local